# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if and .Values.lfx.swagger_ui.enabled .Values.heimdall.enabled }}
apiVersion: heimdall.dadrus.github.com/v1alpha4
kind: RuleSet
metadata:
  name: lfx-swagger-ui
  namespace: lfx
spec:
  rules:
    - id: "rule:lfx:swagger_ui:public"
      match:
        methods:
          - GET
        routes:
          - path: /docs/
          - path: /docs/**
      execute:
        - authorizer: allow_all
{{- end }}
