# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if and .Values.lfx.whoami.enabled (or
  .Values.gateway.enabled .Values.lfx.parentGateway.enabled) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
{{- if .Values.gateway.enabled }}
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name | default "lfx-platform-gateway" }}
      sectionName: {{ include "lfx-platform.default-listener" . }}
      namespace: {{ .Release.Namespace }}
{{- else }}
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.lfx.parentGateway.name }}
      sectionName: {{ .Values.lfx.parentGateway.sectionName }}
      namespace: {{ .Values.lfx.parentGateway.namespace }}
{{- end }}
  hostnames:
    - "lfx-api.{{ .Values.lfx.domain }}"
  rules:
    # Main application endpoints (with authentication)
    - matches:
      - path:
          type: Exact
          value: /whoami
      {{- if .Values.heimdall.enabled }}
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: heimdall
      {{- end }}
      backendRefs:
        - group: ""
          kind: Service
          name: whoami
          port: 80
          weight: 1
{{- end }}
