# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if and .Values.lfx.whoami.enabled .Values.traefik.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.traefik.gateway.name }}
    namespace: {{ .Release.Namespace }}
  hostnames:
  - "lfx-api.{{ .Values.lfx.domain }}"
  rules:
  # Main application endpoints (with authentication)
  - matches:
    - path:
        type: Exact
        value: /whoami
    {{- if .Values.heimdall.enabled }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: heimdall
    {{- end }}
    backendRefs:
    - name: whoami
      port: 80
{{- end }}
