# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{ if and .Values.mailpit.enabled (or
  .Values.gateway.enabled .Values.lfx.parentGateway.enabled) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.names.fullname" .Subcharts.mailpit }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
{{- if .Values.gateway.enabled }}
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name | default "lfx-platform-gateway" }}
      sectionName: {{ include "lfx-platform.default-listener" . }}
      namespace: {{ .Release.Namespace }}
{{- else }}
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.lfx.parentGateway.name }}
      sectionName: {{ .Values.lfx.parentGateway.sectionName }}
      namespace: {{ .Values.lfx.parentGateway.namespace }}
{{- end }}
  hostnames:
    - 'mailpit.{{ .Values.lfx.domain }}'
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "common.names.fullname" .Subcharts.mailpit }}-http
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.mailpit.service.http.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
