# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-platform
description: LFX Platform V2 Helm chart
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://github.com/linuxfoundation/lfx-v2-helm/raw/main/img/lfx-logo-color.svg
dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    version: ~36.2.0
    condition: traefik.enabled
  - name: openfga
    repository: https://openfga.github.io/helm-charts
    version: ~0.2.35
    condition: lfx.openfga_enabled
  - name: heimdall
    repository: https://dadrus.github.io/heimdall/charts
    version: ~0.15.6
    condition: heimdall.enabled
  - name: nats
    repository: https://nats-io.github.io/k8s/helm/charts/
    version: ~1.3.8
    condition: nats.enabled
  - name: opensearch
    repository: https://opensearch-project.github.io/helm-charts/
    version: ~2.34.0
    condition: opensearch.enabled
