# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
# LFX global values
lfx:
  # Domain configuration
  domain: k8s.orb.local

  # Common image settings
  image:
    registry: linuxfoundation
    pullPolicy: IfNotPresent

# Traefik configuration
traefik:
  enabled: true
  # Additional traefik configuration can be added here
  # Values will be merged with the subchart's values
  ingressRoute:
    dashboard:
      enabled: true
      # Additional dashboard configuration

# OpenFGA configuration
openfga:
  enabled: true

  # Disable playground by default
  playground:
    enabled: false

  # Use PostgreSQL
  datastore:
    engine: postgres
    # Must override uriSecret if setting postgresql.enabled to false.
    uriSecret: openfga-postgresql-client
    migrationType: initContainer

  # PostgreSQL subchart configuration
  postgresql:
    enabled: true
    auth:
      username: openfga
      database: openfga
      existingSecret: openfga-postgresql-server

  # Additional OpenFGA configuration
  replicaCount: 1

# Heimdall configuration
heimdall:
  enabled: true

  image:
    tag: 0.16.6

  deployment:
    replicaCount: 1
    autoscaling:
      enabled: false
    volumes:
      - name: heimdall-signer-cert
        secret:
          secretName: heimdall-signer-cert
    volumeMounts:
      - name: heimdall-signer-cert
        mountPath: "/heimdall/cert/"

  log:
    format: gelf
    level: info

  providers:
    kubernetes: {}

  serve:
    trusted_proxies:
      - 192.168.0.0/16

  mechanisms:
    authenticators:
      - id: anonymous_authenticator
        type: anonymous
        config:
          subject: "_anonymous"
    authorizers:
      - id: allow_all
        type: allow
      - id: deny_all
        type: deny
    finalizers:
      - id: create_jwt
        type: jwt
        config:
          signer:
            key_store:
              path: /heimdall/cert/signer.pem

  default_rule:
    execute:
      - authenticator: anonymous_authenticator
      - authorizer: deny_all
      - finalizer: create_jwt

  extraArgs:
    - "--insecure"

# NATS configuration
nats:
  enabled: true
  config:
    cluster:
      enabled: true
      replicas: 3

    # NATS Box for management operations
    natsBox:
      enabled: true

    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

    # JetStream configuration
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        size: 1Gi

# OpenSearch configuration
opensearch:
  enabled: true
  singleNode: true
  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
    - name: DISABLE_SECURITY_PLUGIN
      value: "true"

# Mailpit configuration
mailpit:
  enabled: true

# Authelia configuration
authelia_enabled: true
authelia:
  pod:
    extraVolumes:
      - name: authelia-users
        configMap:
          name: authelia-users
          items:
            - key: users_database.yml
              path: users_database.yml
    extraVolumeMounts:
      - name: authelia-users
        mountPath: /config2
        subpath: users_database.yml
  configMap:
    log:
      format: json
    session:
      cookies:
        - domain: k8s.orb.local
          subdomain: auth
    totp:
      disable: true
    webauthn:
      disable: true
    authentication_backend:
      file:
        enabled: true
        path: /config2/users_database.yml
    access_control:
      default_policy: one_factor
    storage:
      local:
        enabled: true
    notifier:
      smtp:
        enabled: true
        address: "smtp://lfx-platform-mailpit-smtp.lfx.svc.cluster.local:25"
        username: ""
        password:
          disabled: true
        disable_require_tls: true
    identity_providers:
      oidc:
        enabled: true
        jwks:
          - key_id: "1"
            algorithm: "RS256"
            key:
              path: /secrets/authelia-jwks-keys/jwks-key-1.pem
        clients:
          - client_id: heimdall
            client_name: Heimdall backend
            client_secret:
              path: /secrets/authelia-clients-hashed/heimdall
            public: false
            scopes:
              - none
            grant_types:
              - client_credentials
            authorization_policy: one_factor
            token_endpoint_auth_method: client_secret_basic
          - client_id: m2m_test
            client_name: M2M Test Client
            client_secret:
              path: /secrets/authelia-clients-hashed/m2m_test
            public: false
            scopes:
              - none
            audience:
              - "http://lfx-api.k8s.orb.local/"
            grant_types:
              - client_credentials
            authorization_policy: one_factor
            token_endpoint_auth_method: client_secret_basic
          - client_id: token_helper
            client_name: Token Helper CLI
            public: true
            redirect_uris:
              - "http://localhost:55001/callback"
            scopes:
              - openid
              - email
              - profile
              - offline_access
            audience:
              - "http://lfx-api.k8s.orb.local/"
            grant_types:
              - authorization_code
              - refresh_token
            authorization_policy: one_factor
  ingress:
    enabled: true
  secret:
    additionalSecrets:
      authelia-jwks-keys: {}
      authelia-clients-hashed: {}
  persistence:
    enabled: true

authelia_generate_jwks:
  enabled: true

authelia_client_generation:
  enabled: true
  clients:
    - heimdall
    - m2m_test

authelia_user_generation:
  enabled: true
  users:
    - project_super_admin
    - project_admin_1
    - project_admin_2
    - committee_member_1
    - committee_member_2

# Additional services. These will be included in the future when LFX platform
# services are added.
additionalServices:
  enabled: false
  # The following services will be added in the future
  # fgaSync:
  #   enabled: false
  # accessCheck:
  #   enabled: false
  # indexer:
  #   enabled: false
  # querySvc:
  #   enabled: false
  # projectsApi:
  #   enabled: false
