# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
# lfx specific values
lfx:
  # Domain configuration
  domain: k8s.orb.local
  # Namespace for platform components
  namespace: lfx
  # Common image settings
  image:
    registry: linuxfoundation
    pullPolicy: IfNotPresent
  # Subchart toggles
  openfga_enabled: true

# Traefik configuration
traefik:
  enabled: true
  # Additional traefik configuration can be added here
  # Values will be merged with the subchart's values
  ingressRoute:
    dashboard:
      enabled: true
      # Additional dashboard configuration

# OpenFGA configuration
openfga:
  # Disable playground by default
  playground:
    enabled: false
    # Configure PostgreSQL dependency
    postgres:
      enabled: true
      # Default PostgreSQL configuration
      auth:
        username: openfga
        database: openfga
        # checkov:skip=CKV_SECRET_6: value is a reference, not a secret
        existingSecret: openfga-postgresql-server

    # External PostgreSQL configuration
    datastore:
      # Set existingSecret with connection string when using external PostgreSQL
      # The secret should contain a key named "uri" with the connection string
      # existingSecret: openfga-postgresql-client

    # Use either integrated PostgreSQL or external PostgreSQL
    # This will be resolved in the subchart's templates

  # Additional OpenFGA configuration
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Heimdall configuration
heimdall:
  enabled: true
  replicaCount: 1

  # Integration with Authelia
  autheliaIntegration:
    enabled: true
    host: auth.${global.domain}

  # Secret configuration
  # checkov:skip=CKV_SECRET_6: values are a references, not secrets
  secretsRef: heimdall-secrets
  certsSecretRef: heimdall-certs

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# NATS configuration
nats:
  enabled: true
  cluster:
    enabled: true
    replicas: 3

  # JetStream configuration
  jetstream:
    enabled: true
    fileStorage:
      enabled: true
      size: 1Gi

  # NATS Box for management operations
  natsBox:
    enabled: true

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Additional services. These will be included in the future when LFX platform
# services are added.
additionalServices:
  enabled: false
  # The following services will be added in the future
  # fgaSync:
  #   enabled: false
  # accessCheck:
  #   enabled: false
  # indexer:
  #   enabled: false
  # querySvc:
  #   enabled: false
  # projectsApi:
  #   enabled: false
