# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
# LFX global values
lfx:
  # Domain configuration
  domain: k8s.orb.local
  # Namespace for platform components
  namespace: lfx
  # Common image settings
  image:
    registry: linuxfoundation
    pullPolicy: IfNotPresent
  # Subchart toggles
  openfga_enabled: true

# Traefik configuration
traefik:
  enabled: true
  # Additional traefik configuration can be added here
  # Values will be merged with the subchart's values
  ingressRoute:
    dashboard:
      enabled: true
      # Additional dashboard configuration

# OpenFGA configuration
openfga:
  # Disable playground by default
  playground:
    enabled: false

  # Use PostgreSQL
  datastore:
    engine: postgres
    # Must override uriSecret if setting postgresql.enabled to false.
    uriSecret: openfga-postgresql-client
    migrationType: initContainer

  # PostgreSQL subchart configuration
  postgresql:
    enabled: true
    auth:
      username: openfga
      database: openfga
      existingSecret: openfga-postgresql-server

  # Additional OpenFGA configuration
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Heimdall configuration
heimdall:
  enabled: true
  replicaCount: 1

  # Integration with Authelia
  autheliaIntegration:
    enabled: true
    host: auth.${lfx.domain}

  # Secret configuration
  secretsRef: heimdall-secrets
  certsSecretRef: heimdall-certs

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# NATS configuration
nats:
  enabled: true
  config:
    cluster:
      enabled: true
      replicas: 3

    # NATS Box for management operations
    natsBox:
      enabled: true

    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

    # JetStream configuration
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        size: 1Gi

# Additional services. These will be included in the future when LFX platform
# services are added.
additionalServices:
  enabled: false
  # The following services will be added in the future
  # fgaSync:
  #   enabled: false
  # accessCheck:
  #   enabled: false
  # indexer:
  #   enabled: false
  # querySvc:
  #   enabled: false
  # projectsApi:
  #   enabled: false
