# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{ if .Values.heimdall.enabled -}}
{{/*
Generate a cert for Heimdall on install of Chart
  TODO: Create RBAC rule to limit secret access to heimdall Pods
*/}}
{{- $heimdallCert := genPrivateKey "rsa" -}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: heimdall-signer-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: heimdall
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
data: 
  "signer.pem": "{{ $heimdallCert | b64enc }}"
{{- end }}
