# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if and .Values.authelia.enabled .Values.authelia_user_generation.enabled }}
{{- $user_pws := dict }}
{{- range $index, $username := .Values.authelia_user_generation.users }}
{{- $user_pws = set $user_pws $username (randAlphaNum 20) }}
{{- end }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: authelia
data:
  {{- range $username, $pw := $user_pws }}
  {{ $username }}: {{ b64enc $pw }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: authelia
data:
  users_database.yml: |
    users:
      {{- range $username, $pw := $user_pws }}
      {{ $username }}:
        displayname: {{ $username | title | replace "_" " " }}
        password: '{{ bcrypt $pw }}'
        email: {{ $username }}@example.com
      {{- end }}
{{- end }}
