# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if and .Values.authelia_enabled .Values.authelia_client_generation.enabled }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authelia-clients
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: authelia
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  {{- range $index, $client := .Values.authelia_client_generation.clients }}
  {{ $client }}: {{ randAlphaNum 32| b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authelia-clients-hashed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: authelia
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  {{- range $key, $val := (lookup "v1" "Secret" .Release.Namespace "authelia-clients").data }}
  {{ $key | quote }}: {{ bcrypt ($val | b64dec) | b64enc }}
  {{- end }}

{{- end }}
