# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if and .Values.openfga.enabled .Values.openfga.postgresql.enabled -}}
{{/*
Generate or lookup existing password for OpenFGA database
*/}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.openfga.postgresql.auth.existingSecret -}}
{{- $openfga_db_pass := "" -}}
{{- if $existingSecret -}}
  {{- $openfga_db_pass = $existingSecret.data.password | b64dec -}}
{{- else -}}
  {{- $openfga_db_pass = randAlphaNum 32 -}}
{{- end -}}

{{- $existingPostgresSecret := lookup "v1" "Secret" .Release.Namespace .Values.openfga.postgresql.auth.existingSecret -}}
{{- $postgres_admin_pass := "" -}}
{{- if $existingPostgresSecret -}}
  {{- $postgres_admin_pass = index $existingPostgresSecret.data "postgres-password" | b64dec -}}
{{- else -}}
  {{- $postgres_admin_pass = randAlphaNum 32 -}}
{{- end -}}

{{- $replication_pass := "" -}}
{{- if $existingPostgresSecret -}}
  {{- $replication_pass = index $existingPostgresSecret.data "replication-password" | b64dec -}}
{{- else -}}
  {{- $replication_pass = randAlphaNum 32 -}}
{{- end -}}

# Client secret with the URI for OpenFGA to connect to PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openfga.datastore.uriSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfga
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  uri: {{ printf
    "postgres://openfga:%v@%v-postgresql:%v/openfga?sslmode=disable"
      $openfga_db_pass
      .Release.Name
      (or
        (and
          .Values.openfga.postgresql.primary
          .Values.openfga.postgresql.primary.service.ports.postgresql
        )
        5432
      )
    | b64enc
  }}
---
# Server secret with the passwords for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openfga.postgresql.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfga
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  password: {{ $openfga_db_pass | b64enc }}
  # Generate additional random passwords for PostgreSQL roles
  postgres-password: {{ $postgres_admin_pass | b64enc }}
  replication-password: {{ $replication_pass | b64enc }}
{{- end }}
