# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.openfga.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openfga-model
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfga
data:
  lfx-access-model.fga.json: |-
    {
      "type_definitions": [
        {
          "type": "user",
          "relations": {}
        },
        {
          "type": "group",
          "relations": {
            "member": {
              "this": {}
            }
          },
          "metadata": {
            "relations": {
              "member": {
                "directly_related_user_types": [
                  {
                    "type": "user"
                  }
                ]
              }
            }
          }
        },
        {
          "type": "project",
          "relations": {
            "viewer": {
              "union": {
                "child": [
                  {
                    "this": {}
                  },
                  {
                    "computedUserset": {
                      "relation": "member",
                      "object": "group:viewers"
                    }
                  }
                ]
              }
            },
            "writer": {
              "union": {
                "child": [
                  {
                    "this": {}
                  },
                  {
                    "computedUserset": {
                      "relation": "member",
                      "object": "group:writers"
                    }
                  }
                ]
              }
            },
            "admin": {
              "union": {
                "child": [
                  {
                    "this": {}
                  },
                  {
                    "computedUserset": {
                      "relation": "member",
                      "object": "group:admins"
                    }
                  }
                ]
              }
            }
          },
          "metadata": {
            "relations": {
              "viewer": {
                "directly_related_user_types": [
                  {
                    "type": "user"
                  }
                ]
              },
              "writer": {
                "directly_related_user_types": [
                  {
                    "type": "user"
                  }
                ]
              },
              "admin": {
                "directly_related_user_types": [
                  {
                    "type": "user"
                  }
                ]
              }
            }
          }
        }
      ]
    }
  lfx-global-groups.json: |-
    {
      "writes": [
        {
          "tuple": {
            "object": "group:admins",
            "relation": "member",
            "user": "user:project_super_admin"
          }
        },
        {
          "tuple": {
            "object": "group:writers",
            "relation": "member",
            "user": "user:project_writer"
          }
        },
        {
          "tuple": {
            "object": "group:viewers",
            "relation": "member",
            "user": "user:project_viewer"
          }
        }
      ]
    }
{{- end }}
