# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if and .Values.lfx.openfga_enabled (not .Values.openfga.postgresql.enabled) }}
# Generate a random password for OpenFGA database
{{- $openfga_db_pass := randAlphaNum 128 | b64enc }}

# Client secret with the URI for OpenFGA to connect to PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openfga.datastore.uriSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfga
type: Opaque
data:
  uri: {{ printf "postgres://openfga:%s@openfga-postgresql:5432/openfga?sslmode=disable" $openfga_db_pass | b64enc }}
---
# Server secret with the passwords for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openfga.postgresql.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfga
type: Opaque
data:
  password: {{ $openfga_db_pass }}
  # Generate additional random passwords for PostgreSQL roles
  postgres-password: {{ randAlphaNum 128 | b64enc }}
  replication-password: {{ randAlphaNum 128 | b64enc }}
{{- end }}
