---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: MegaLinter

"on":
  pull_request: null

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
        with:
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter
        id: ml
        # Use the Documentation flavor.
        uses: oxsecurity/megalinter/flavors/documentation@5a91fb06c83d0e69fbd23756d47438aa723b4a5a  # 8.7.0
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Allow GITHUB_TOKEN for working around rate limits (aquasecurity/trivy#7668).
          REPOSITORY_TRIVY_UNSECURED_ENV_VARIABLES: GITHUB_TOKEN

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f  # v3.28.18
        with:
          sarif_file: 'megalinter-reports/megalinter-report.sarif'
